# This Makefile expects mingw/msys environment and GNU Make.
#
# Targets:
# --------
#   make all        - Makes mCtrl.dll and import libs (this is default target).
#   make doc        - Generates documentation (requires doxygen).
#   make examples   - Makes examples in examples/ subdirectory.
#   make clean      - Deletes mCtrl.dll objects and binary.
#   make distclean  - Deletes all generated files.
#
# Useful variables:
# -----------------
#   PREFIX=<prefix> - Specifies gcc toolchain prefix.
#                     (e.g. 'make PREFIX=x86_64-w64-mingw32-' can build 
#                     x86_64 binaries, if you have mingw-w64 installed and
#                     its bin directory in PATH.)
#   DEBUG=<number>  - Sets debugging level. Default is 0. Possible values:
#                         0 = no debugging (i.e. release build)
#                         1 = enables some asserts and traces
#                         2 = as 1 and also tracks mc_malloc/mc_free usage


BASENAME = mCtrl.dll

INCDIR = include
SRCDIR = src
BINDIR = bin
OBJDIR = obj
LIBDIR = lib

CC = $(PREFIX)gcc -c
LD = $(PREFIX)gcc
WINDRES = $(PREFIX)windres
DLLTOOL = $(PREFIX)dlltool
DEP = $(PREFIX)gcc -x c -MM -MG
RM = rm -rf

INCLUDES = -I$(INCDIR) -I$(SRCDIR)


ifneq ($(filter $(PREFIX), x86_64-w64-mingw32- i686-w64-mingw32-),)
    # mingw-w64 does not support lower _WIN32_IE then 0x0501
    WINVER = -D_WIN32_IE=0x0501 -D_WIN32_WINNT=0x0501 -DWINVER=_WIN32_WINNT
else
    # IE 5.0 was the oldest installed with Win2K, so we want to support it:
    WINVER = -D_WIN32_IE=0x0500 -D_WIN32_WINNT=0x0501 -DWINVER=_WIN32_WINNT
    
    # We need extra headers filling gaps in w32api 3.13 of mingw project
    # (some COM/OLE related):
    INCLUDES += -I$(SRCDIR)/com
endif

UNICODE = -DUNICODE -D_UNICODE

CPPFLAGS += -DMCTRL_BUILD $(UNICODE) $(WINVER) $(INCLUDES)
CFLAGS += -Wall
LDFLAGS += -mwindows -shared -Wl,--kill-at
LIBS += -lcomctl32 -lole32 -loleaut32

ifndef DEBUG
    DEBUG = 0
endif
ifneq ($(DEBUG),0)
	CPPFLAGS += -DDEBUG=$(DEBUG)
	CFLAGS += -g -O0
else
	CFLAGS += -O3
	LDFLAGS += -s
endif

PUBLIC_HEADERS = $(wildcard $(INCDIR)/*.h $(INCDIR)/mCtrl/*.h)
HEADERS = $(PUBLIC_HEADERS) $(wildcard $(SRCDIR)/*.h)
C_SOURCES = $(wildcard $(SRCDIR)/*.c)
RC_SOURCES = $(wildcard $(SRCDIR)/*.rc)
SOURCES = $(C_SOURCES) $(RC_SOURCES)
C_OBJECTS = $(addprefix $(OBJDIR)/, $(notdir $(addsuffix .o,$(basename $(C_SOURCES)))))
RC_OBJECTS = $(addprefix $(OBJDIR)/, $(notdir $(addsuffix .o,$(basename $(RC_SOURCES)))))
OBJECTS = $(addprefix $(OBJDIR)/, $(notdir $(addsuffix .o,$(basename $(SOURCES)))))
TARGET = $(BINDIR)/$(BASENAME)
TARGET_LIB = $(LIBDIR)/lib$(basename $(BASENAME)).a


####################
# The main targets #
####################

.PHONY: all examples doc clean distclean

all: $(TARGET) $(TARGET_LIB)

examples:
	(cd examples && $(MAKE))

doc:
	doxygen
	
clean:
	$(RM) $(OBJECTS) 
	$(RM) $(TARGET_LIB)
	$(RM) $(TARGET)
	
distclean: clean
	(cd examples && $(MAKE) clean)
	$(RM) doc/*


################
# Dependencies #
################

# The dependencies are automatically detected by scanning all sources in src/.

Makefile.dep: $(SOURCES) $(HEADERS)
	$(RM) Makefile.dep
	echo "# This file is automatically (re)generated by Makefile when any source" >> Makefile.dep
	echo "# is modified or when new source is added into the src/ directory." >> Makefile.dep
	echo "# Do not modify this file manually." >> Makefile.dep
	echo >> Makefile.dep
	echo >> Makefile.dep
	$(DEP) $(CPPFLAGS) $(SOURCES) | sed "/\.o:/ s/^/$(subst /,\\/,$(OBJDIR))\//" >> Makefile.dep
	echo "$(RC_OBJECTS): $(wildcard $(SRCDIR)/res/*)" >> Makefile.dep
	echo >> Makefile.dep

include Makefile.dep


###############
# Build rules #
###############

$(TARGET) $(TARGET_LIB): $(OBJECTS)
	$(LD) $(LDFLAGS) $^ -o $@ $(LIBS)
	$(DLLTOOL) --kill-at --output-lib $(TARGET_LIB) --dllname $(notdir $@) $^

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CPPFLAGS) $(CFLAGS) $< -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.rc
	$(WINDRES) $(filter-out -DUNICODE -D_UNICODE, $(CPPFLAGS)) -I$(SRCDIR) $< $@


