/* This file is generated automatically from 'resource.h.in' by script 'mkres.sh'.
 * Do not edit this file manually.
 */

/*
 * Copyright (c) 2008-2015 Martin Mitas
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#ifndef MC_RESOURCE_H
#define MC_RESOURCE_H


/********************
 *** Resource IDs ***
*********************/

#define IDR_GLYPHS                100

#define IDR_EXPAND_GLYPHS_19      101
#define IDR_EXPAND_GLYPHS_24      102
#define IDR_EXPAND_GLYPHS_29      103

#define IDR_CURSOR_DIVIDER_H      104
#define IDR_CURSOR_DIVIDER_V      105
#define IDR_CURSOR_DIVOPEN_H      106
#define IDR_CURSOR_DIVOPEN_V      107


/******************
 *** String IDs ***
 ******************/

#define IDS_EXPAND_MOREDETAILS    0
#define IDS_EXPAND_FEWERDETAILS   1


#endif  /* MC_RESOURCE_H */
